/*
 * File: leg_conv_fwd.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 23-Oct-2025 11:31:13
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_conv_fwd.h"

#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV_FWD
 *     T_real = LEG_CONV_FWD(T1,T2,PHI1,PHI2)
 *
 * Arguments    : double T1
 *                double T2
 *                double phi1
 *                double phi2
 *                double T_real[2]
 * Return Type  : void
 */
void leg_conv_fwd(double T1, double T2, double phi1, double phi2, double T_real[2])
{
  double b_t42_tmp;
  double c_t42_tmp;
  double d_t42_tmp;
  double t11_tmp;
  double t15_tmp;
  double t27_tmp;
  double t29_tmp;
  double t40;
  double t42;
  double t42_tmp;
  double t4_tmp;
  double t5_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     23-Oct-2025 11:26:33 */
  t4_tmp = cos(phi1);
  t5_tmp = sin(phi1);
  t11_tmp = phi1 + phi2;
  t15_tmp = cos(t11_tmp);
  t11_tmp = sin(t11_tmp);
  t27_tmp = t15_tmp * t15_tmp;
  t29_tmp = t11_tmp * t11_tmp;
  t42_tmp = t5_tmp * t11_tmp;
  b_t42_tmp = t4_tmp * t15_tmp;
  c_t42_tmp = t4_tmp * t4_tmp;
  d_t42_tmp = t5_tmp * t5_tmp;
  t42 = sqrt(
      ((((t27_tmp * 0.0676 + t29_tmp * 0.0676) + c_t42_tmp * 0.047524) + d_t42_tmp * 0.047524) + b_t42_tmp * 0.11336) +
      t42_tmp * 0.11336);
  t40 = 1.0 / (t4_tmp * t11_tmp - t5_tmp * t15_tmp);
  T_real[0] =
      T2 * t40 * t42 * -17.642907551164431 +
      T1 * t40 * t42 *
          (((((((((t27_tmp * 130.0 + t29_tmp * 130.0) - 0.0 * t11_tmp * 109.0) + t42_tmp * 109.0) + b_t42_tmp * 109.0) +
               t4_tmp * 0.0 * 109.0) +
              0.0 * t15_tmp * 109.0) -
             t5_tmp * 0.0 * 109.0) -
            t11_tmp * 0.0 * 260.0) +
           t15_tmp * 0.0 * 260.0) *
          (2293.5779816513759 /
           (((((((((((((t27_tmp * 16900.0 + t29_tmp * 16900.0) - 0.0 * t5_tmp * 23762.0) + t4_tmp * 0.0 * 23762.0) -
                     0.0 * t11_tmp * 28340.0) +
                    t42_tmp * 28340.0) +
                   b_t42_tmp * 28340.0) +
                  t4_tmp * 0.0 * 28340.0) +
                 0.0 * t15_tmp * 28340.0) -
                t5_tmp * 0.0 * 28340.0) -
               t11_tmp * 0.0 * 33800.0) +
              t15_tmp * 0.0 * 33800.0) +
             c_t42_tmp * 11881.0) +
            d_t42_tmp * 11881.0));
  T_real[1] = -T1;
}

/*
 * File trailer for leg_conv_fwd.c
 *
 * [EOF]
 */
