/*
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 23-Oct-2025 11:30:32
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_conv.h"

#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI2)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi2
 *                double T[2]
 * Return Type  : void
 */
void leg_conv(double F, double Tp, double phi1, double phi2, double T[2])
{
  double a_tmp;
  double t10_tmp;
  double t11_tmp;
  double t12_tmp;
  double t21;
  double t23;
  double t30;
  double t32;
  double t33;
  double t34;
  double t36;
  double t4;
  double t5;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     23-Oct-2025 11:26:33 */
  t4 = cos(phi1);
  t5 = sin(phi1);
  t10_tmp = phi1 + phi2;
  t11_tmp = cos(t10_tmp);
  t12_tmp = sin(t10_tmp);
  t21 = t11_tmp * 0.26;
  t23 = t12_tmp * 0.26;
  t30 = t21 + t4 * 0.218;
  a_tmp = (0.0 - t23) - t5 * 0.218;
  t33 = a_tmp * a_tmp;
  t32 = t30 * t30;
  t34 = 1.0 / t33;
  t36 = 1.0 / (t32 + t33);
  t4 = t4 * 0.218 + t11_tmp * 0.26;
  t10_tmp = t5 * 0.218 + t12_tmp * 0.26;
  T[0] = -Tp * t33 * t36 * (t32 * t34 + 1.0);
  T[1] = F *
             (t12_tmp * (t11_tmp * 0.26 + cos(phi1) * 0.218) * 0.52 -
              t11_tmp * (t12_tmp * 0.26 + sin(phi1) * 0.218) * 0.52) *
             -0.5 / sqrt(t4 * t4 + t10_tmp * t10_tmp) -
         Tp * t33 * t36 * ((0.0 - t23) / a_tmp + t30 * t34 * t21);
}

/*
 * File trailer for leg_conv.c
 *
 * [EOF]
 */
