/*
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 23-Oct-2025 11:29:48
 */

/* Include Files */
#include "bipedal_wheel_controller/vmc/leg_spd.h"

#include <math.h>

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI2,PHI1,PHI2)
 *
 * Arguments    : double dphi1
 *                double dphi2
 *                double phi1
 *                double phi2
 *                double spd[2]
 * Return Type  : void
 */
void leg_spd(double dphi1, double dphi2, double phi1, double phi2, double spd[2])
{
  double t10;
  double t22;
  double t29_tmp;
  double t3;
  double t30;
  double t33_tmp;
  double t35;
  double t37;
  double t8;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     23-Oct-2025 11:26:32 */
  t3 = sin(phi1);
  t8 = phi1 + phi2;
  t9 = cos(t8);
  t10 = sin(t8);
  t22 = t10 * 0.26;
  t29_tmp = t9 * 0.26 + cos(phi1) * 0.218;
  t30 = t10 * 0.26 + t3 * 0.218;
  t8 = (0.0 - t22) - t3 * 0.218;
  t3 = t8 * t8;
  t33_tmp = t29_tmp * t29_tmp;
  t35 = 1.0 / t3;
  t37 = 1.0 / (t33_tmp + t3);
  spd[0] = dphi2 / sqrt(t33_tmp + t30 * t30) * (t9 * t30 * 0.52 - t10 * t29_tmp * 0.52) / 2.0;
  spd[1] =
      -dphi1 * t3 * t37 * (t33_tmp * t35 + 1.0) - dphi2 * t3 * t37 * ((0.0 - t22) / t8 + t29_tmp * t35 * (t9 * 0.26));
}

/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
